"""Initial migration with all models

Revision ID: 093f27321f56
Revises: 
Create Date: 2025-11-15 10:21:31.863558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '093f27321f56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='Telegram first name'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='Telegram last name'),
    sa.Column('balance_credits', sa.Integer(), nullable=False, comment='Количество кредитов (1 кредит = 1 действие)'),
    sa.Column('subscription_type', sa.Enum('BASIC', 'PRO', 'PREMIUM', name='subscription_type_enum'), nullable=True, comment='Тип активной подписки'),
    sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True, comment='Дата окончания подписки'),
    sa.Column('freemium_actions_used', sa.Integer(), nullable=False, comment='Количество использованных Freemium действий в текущем месяце'),
    sa.Column('freemium_reset_at', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего сброса Freemium счётчика'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли пользователь'),
    sa.Column('is_banned', sa.Boolean(), nullable=False, comment='Забанен ли пользователь'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_subscription_end', 'users', ['subscription_end'], unique=False)
    op.create_index('idx_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False, comment='Уникальный ID сессии чата'),
    sa.Column('base_image_url', sa.String(length=500), nullable=True, comment='URL базового изображения для редактирования'),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='История сообщений в формате JSONB'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли сессия чата'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_is_active', 'chat_histories', ['is_active'], unique=False)
    op.create_index('idx_chat_session_id', 'chat_histories', ['session_id'], unique=False)
    op.create_index('idx_chat_user_id_created', 'chat_histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_histories_id'), 'chat_histories', ['id'], unique=False)
    op.create_index(op.f('ix_chat_histories_session_id'), 'chat_histories', ['session_id'], unique=True)
    op.create_index(op.f('ix_chat_histories_user_id'), 'chat_histories', ['user_id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('type', sa.Enum('FITTING', 'EDITING', name='generation_type_enum'), nullable=False, comment='Тип генерации (примерка или редактирование)'),
    sa.Column('user_photo_url', sa.String(length=500), nullable=True, comment='URL фото пользователя/модели (для примерки)'),
    sa.Column('item_photo_url', sa.String(length=500), nullable=True, comment='URL фото одежды/аксессуара (для примерки)'),
    sa.Column('accessory_zone', sa.String(length=50), nullable=True, comment='Зона размещения аксессуара (голова, шея, руки, ноги)'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='Текстовый промпт для генерации/редактирования'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL сгенерированного изображения'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Статус: pending, processing, completed, failed'),
    sa.Column('task_id', sa.String(length=255), nullable=True, comment='ID задачи Celery для отслеживания'),
    sa.Column('credits_spent', sa.Integer(), nullable=False, comment='Количество потраченных кредитов'),
    sa.Column('tokens_used', sa.Numeric(precision=10, scale=2), nullable=True, comment='Количество использованных токенов (для редактирования с AI)'),
    sa.Column('has_watermark', sa.Boolean(), nullable=False, comment='Наличие водяного знака (Freemium)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке при генерации'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gen_task_id', 'generations', ['task_id'], unique=False)
    op.create_index('idx_gen_type_status', 'generations', ['type', 'status'], unique=False)
    op.create_index('idx_gen_user_id_created', 'generations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    op.create_index(op.f('ix_generations_task_id'), 'generations', ['task_id'], unique=False)
    op.create_index(op.f('ix_generations_type'), 'generations', ['type'], unique=False)
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('yookassa_id', sa.String(length=255), nullable=False, comment='ID платежа в ЮKassa'),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False, comment='Ключ идемпотентности для предотвращения дублей'),
    sa.Column('payment_type', sa.Enum('SUBSCRIPTION', 'CREDITS', name='payment_type_enum'), nullable=False, comment='Тип платежа (подписка или кредиты)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCEEDED', 'CANCELLED', 'REFUNDED', name='payment_status_enum'), nullable=False, comment='Статус платежа'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма платежа в рублях'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма налога НПД 4%'),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Комиссия ЮKassa 2.8%'),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Чистая сумма после вычета налогов и комиссий'),
    sa.Column('credits_awarded', sa.Integer(), nullable=True, comment='Количество начисленных кредитов'),
    sa.Column('subscription_type_awarded', sa.String(length=50), nullable=True, comment='Тип подписки (basic, pro, premium)'),
    sa.Column('subscription_duration_days', sa.Integer(), nullable=True, comment='Длительность подписки в днях (обычно 30)'),
    sa.Column('tokens_used', sa.Numeric(precision=10, scale=2), nullable=True, comment='Количество использованных токенов OpenRouter'),
    sa.Column('extra_data', sa.Text(), nullable=True, comment='Дополнительные данные в JSON формате'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание платежа для пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_idempotency_key', 'payments', ['idempotency_key'], unique=False)
    op.create_index('idx_status_type', 'payments', ['status', 'payment_type'], unique=False)
    op.create_index('idx_user_id_created', 'payments', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_yookassa_id', 'payments', ['yookassa_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_yookassa_id'), 'payments', ['yookassa_id'], unique=True)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False, comment='ID пользователя, который пригласил (реферер)'),
    sa.Column('referred_id', sa.Integer(), nullable=False, comment='ID приглашённого пользователя (реферал)'),
    sa.Column('credits_awarded', sa.Integer(), nullable=False, comment='Количество начисленных кредитов реферу (+10 по умолчанию)'),
    sa.Column('is_awarded', sa.Boolean(), nullable=False, comment='Были ли начислены кредиты (после первого действия реферала)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_is_awarded', 'referrals', ['is_awarded'], unique=False)
    op.create_index('idx_referred_id', 'referrals', ['referred_id'], unique=False)
    op.create_index('idx_referrer_id', 'referrals', ['referrer_id'], unique=False)
    op.create_index('idx_unique_referral', 'referrals', ['referrer_id', 'referred_id'], unique=True)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_is_awarded'), 'referrals', ['is_awarded'], unique=False)
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_is_awarded'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index('idx_unique_referral', table_name='referrals')
    op.drop_index('idx_referrer_id', table_name='referrals')
    op.drop_index('idx_referred_id', table_name='referrals')
    op.drop_index('idx_is_awarded', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_payments_yookassa_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index('idx_yookassa_id', table_name='payments')
    op.drop_index('idx_user_id_created', table_name='payments')
    op.drop_index('idx_status_type', table_name='payments')
    op.drop_index('idx_idempotency_key', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_type'), table_name='generations')
    op.drop_index(op.f('ix_generations_task_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_id'), table_name='generations')
    op.drop_index('idx_gen_user_id_created', table_name='generations')
    op.drop_index('idx_gen_type_status', table_name='generations')
    op.drop_index('idx_gen_task_id', table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_chat_histories_user_id'), table_name='chat_histories')
    op.drop_index(op.f('ix_chat_histories_session_id'), table_name='chat_histories')
    op.drop_index(op.f('ix_chat_histories_id'), table_name='chat_histories')
    op.drop_index('idx_chat_user_id_created', table_name='chat_histories')
    op.drop_index('idx_chat_session_id', table_name='chat_histories')
    op.drop_index('idx_chat_is_active', table_name='chat_histories')
    op.drop_table('chat_histories')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_telegram_id', table_name='users')
    op.drop_index('idx_subscription_end', table_name='users')
    op.drop_index('idx_is_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
